###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"email": "fware@example.org",
  	"password": "pass"
}


###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"email": "facu@mail.com",
  	"password": "pass"
}

###

POST  http://localhost:8000/api/game-invitation/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzODUxMjAxLCJpYXQiOjE3MzM4NDc2MDEsImp0aSI6IjRlMmZjN2YwNGNmYzQwMThhNmRlZjE1Yjg5MGI5MDUwIiwidXNlcl9pZCI6MTB9.MxVyN8xyQdJ1lqLagBsp9ba5o8VyTO5GPV6o666CNeQ

###

GET  http://localhost:8000/api/game-invitations/sent/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzODQ5MTcwLCJpYXQiOjE3MzM4NDU1NzAsImp0aSI6IjdjMmNhN2RkMjlmMTQ0OWU4YjQ3MDRlODU4OWI4NzNiIiwidXNlcl9pZCI6MTJ9.sKYUqXcJMDhfdvEVLVmeyvvJFtVm8J-KnFfwxwsWvSM


###

GET  http://localhost:8000/api/game-invitations/received/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzODQ5MjM5LCJpYXQiOjE3MzM4NDU2MzksImp0aSI6ImJjZDM2M2FiYjYyZDRlMTE4NjRjZWRkN2E5MjIwYjEyIiwidXNlcl9pZCI6MX0._tCjuUziczV3kUOSP14_DbThG5wSGSZ13eavhoSCTRs

###

GET  http://localhost:8000/api/2fa/setup/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyMjk0OTc3LCJpYXQiOjE3MzIyOTEzNzcsImp0aSI6IjJmZjQ4Mjk1MGYwODQyNjJiYmM5ZWRhYzFhOGM5MDU0IiwidXNlcl9pZCI6M30.A8s3N6Ob8qGe87L6AXFINw9A0zoISd5FrtcLmn_IXq0

###

POST  http://localhost:8000/api/2fa/verify-setup/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyMjk0OTc3LCJpYXQiOjE3MzIyOTEzNzcsImp0aSI6IjJmZjQ4Mjk1MGYwODQyNjJiYmM5ZWRhYzFhOGM5MDU0IiwidXNlcl9pZCI6M30.A8s3N6Ob8qGe87L6AXFINw9A0zoISd5FrtcLmn_IXq0
Content-Type: application/json

{
	"otp": "772566"
}

###

POST  http://localhost:8000/api/verify-otp HTTP/1.1
Content-Type: application/json

{
	"otp": "503412",
	"email": "michaelhall@example.com"
}

###
