# Generated by Django 4.2.14 on 2024-09-07 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Username must be at least 4 characters long.'), django.core.validators.RegexValidator(message='Enter a valid username.', regex='^[\\w.@+-]+$')]),
        ),
    ]
