# Generated by Django 4.2.14 on 2024-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_2fa_enabled',
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_method',
            field=models.CharField(choices=[('none', 'None'), ('email', 'Email'), ('qr', 'QR Code')], default='none', max_length=5),
        ),
    ]
