# Generated by Django 4.2.14 on 2024-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_customuser_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_pending',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='pending email address'),
        ),
    ]
