# Generated by Django 4.2.14 on 2024-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_email_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_pending_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
