# Generated by Django 4.2.14 on 2024-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customuser_email_pending_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_upload',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
