# Generated by Django 4.2.14 on 2024-11-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customuser_avatar_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar',
            new_name='avatar_oauth',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email_pending',
            new_name='new_email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email_pending_is_verified',
            new_name='new_email_is_verified',
        ),
    ]
