# Generated by Django 4.2.14 on 2024-11-15 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_customuser_oauth_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='oauth_uid',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_upload',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
