# Generated by Django 4.2.14 on 2024-11-16 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_customuser_oauth_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator], verbose_name='pending email address'),
        ),
    ]
