# Generated by Django 4.2.14 on 2024-11-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_gamestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
