# Generated by Django 4.2.14 on 2024-11-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authenticator_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='authenticator_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_method',
            field=models.CharField(choices=[('none', 'None'), ('email', 'Email'), ('authenticator', 'Authenticator')], default='none', max_length=13),
        ),
    ]
