# Generated by Django 4.2.14 on 2024-11-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_customuser_validation_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='authenticator_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='authenticator_secret',
        ),
    ]
