# Generated by Django 4.2.14 on 2024-12-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_customuser_authenticator_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oauth_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
